<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;
class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kota = [
                ['id'=>1101,'kode_kota'=>'1101','nama_kota'=>'KABUPATEN SIMEULUE','id_provinsi'=>11],
                ['id'=>1102,'kode_kota'=>'1102','nama_kota'=>'KABUPATEN ACEH SINGKIL','id_provinsi'=>11],
                ['id'=>1103,'kode_kota'=>'1103','nama_kota'=>'KABUPATEN ACEH SELATAN','id_provinsi'=>11],
                ['id'=>1104,'kode_kota'=>'1104','nama_kota'=>'KABUPATEN ACEH TENGGARA','id_provinsi'=>11],
                ['id'=>1105,'kode_kota'=>'1105','nama_kota'=>'KABUPATEN ACEH TIMUR','id_provinsi'=>11],
                ['id'=>1106,'kode_kota'=>'1106','nama_kota'=>'KABUPATEN ACEH TENGAH','id_provinsi'=>11],
                ['id'=>1107,'kode_kota'=>'1107','nama_kota'=>'KABUPATEN ACEH BARAT','id_provinsi'=>11],
                ['id'=>1108,'kode_kota'=>'1108','nama_kota'=>'KABUPATEN ACEH BESAR','id_provinsi'=>11],
                ['id'=>1109,'kode_kota'=>'1109','nama_kota'=>'KABUPATEN PIDIE','id_provinsi'=>11],
                ['id'=>1110,'kode_kota'=>'1110','nama_kota'=>'KABUPATEN BIREUEN','id_provinsi'=>11],
                ['id'=>1111,'kode_kota'=>'1111','nama_kota'=>'KABUPATEN ACEH UTARA','id_provinsi'=>11],
                ['id'=>1112,'kode_kota'=>'1112','nama_kota'=>'KABUPATEN ACEH BARAT DAYA','id_provinsi'=>11],
                ['id'=>1113,'kode_kota'=>'1113','nama_kota'=>'KABUPATEN GAYO LUES','id_provinsi'=>11],
                ['id'=>1114,'kode_kota'=>'1114','nama_kota'=>'KABUPATEN ACEH TAMIANG','id_provinsi'=>11],
                ['id'=>1115,'kode_kota'=>'1115','nama_kota'=>'KABUPATEN NAGAN RAYA','id_provinsi'=>11],
                ['id'=>1116,'kode_kota'=>'1116','nama_kota'=>'KABUPATEN ACEH JAYA','id_provinsi'=>11],
                ['id'=>1117,'kode_kota'=>'1117','nama_kota'=>'KABUPATEN BENER MERIAH','id_provinsi'=>11],
                ['id'=>1118,'kode_kota'=>'1118','nama_kota'=>'KABUPATEN PIDIE JAYA','id_provinsi'=>11],
                ['id'=>1171,'kode_kota'=>'1171','nama_kota'=>'KOTA BANDA ACEH','id_provinsi'=>11],
                ['id'=>1172,'kode_kota'=>'1172','nama_kota'=>'KOTA SABANG','id_provinsi'=>11],
                ['id'=>1173,'kode_kota'=>'1173','nama_kota'=>'KOTA LANGSA','id_provinsi'=>11],
                ['id'=>1174,'kode_kota'=>'1174','nama_kota'=>'KOTA LHOKSEUMAWE','id_provinsi'=>11],
                ['id'=>1175,'kode_kota'=>'1175','nama_kota'=>'KOTA SUBULUSSALAM','id_provinsi'=>11],
                ['id'=>1201,'kode_kota'=>'1201','nama_kota'=>'KABUPATEN NIAS','id_provinsi'=>12],
                ['id'=>1202,'kode_kota'=>'1202','nama_kota'=>'KABUPATEN MANDAILING NATAL','id_provinsi'=>12],
                ['id'=>1203,'kode_kota'=>'1203','nama_kota'=>'KABUPATEN TAPANULI SELATAN','id_provinsi'=>12],
                ['id'=>1204,'kode_kota'=>'1204','nama_kota'=>'KABUPATEN TAPANULI TENGAH','id_provinsi'=>12],
                ['id'=>1205,'kode_kota'=>'1205','nama_kota'=>'KABUPATEN TAPANULI UTARA','id_provinsi'=>12],
                ['id'=>1206,'kode_kota'=>'1206','nama_kota'=>'KABUPATEN TOBA SAMOSIR','id_provinsi'=>12],
                ['id'=>1207,'kode_kota'=>'1207','nama_kota'=>'KABUPATEN LABUHAN BATU','id_provinsi'=>12],
                ['id'=>1208,'kode_kota'=>'1208','nama_kota'=>'KABUPATEN ASAHAN','id_provinsi'=>12],
                ['id'=>1209,'kode_kota'=>'1209','nama_kota'=>'KABUPATEN SIMALUNGUN','id_provinsi'=>12],
                ['id'=>1210,'kode_kota'=>'1210','nama_kota'=>'KABUPATEN DAIRI','id_provinsi'=>12],
                ['id'=>1211,'kode_kota'=>'1211','nama_kota'=>'KABUPATEN KARO','id_provinsi'=>12],
                ['id'=>1212,'kode_kota'=>'1212','nama_kota'=>'KABUPATEN DELI SERDANG','id_provinsi'=>12],
                ['id'=>1213,'kode_kota'=>'1213','nama_kota'=>'KABUPATEN LANGKAT','id_provinsi'=>12],
                ['id'=>1214,'kode_kota'=>'1214','nama_kota'=>'KABUPATEN NIAS SELATAN','id_provinsi'=>12],
                ['id'=>1215,'kode_kota'=>'1215','nama_kota'=>'KABUPATEN HUMBANG HASUNDUTAN','id_provinsi'=>12],
                ['id'=>1216,'kode_kota'=>'1216','nama_kota'=>'KABUPATEN PAKPAK BHARAT','id_provinsi'=>12],
                ['id'=>1217,'kode_kota'=>'1217','nama_kota'=>'KABUPATEN SAMOSIR','id_provinsi'=>12],
                ['id'=>1218,'kode_kota'=>'1218','nama_kota'=>'KABUPATEN SERDANG BEDAGAI','id_provinsi'=>12],
                ['id'=>1219,'kode_kota'=>'1219','nama_kota'=>'KABUPATEN BATU BARA','id_provinsi'=>12],
                ['id'=>1220,'kode_kota'=>'1220','nama_kota'=>'KABUPATEN PADANG LAWAS UTARA','id_provinsi'=>12],
                ['id'=>1221,'kode_kota'=>'1221','nama_kota'=>'KABUPATEN PADANG LAWAS','id_provinsi'=>12],
                ['id'=>1222,'kode_kota'=>'1222','nama_kota'=>'KABUPATEN LABUHAN BATU SELATAN','id_provinsi'=>12],
                ['id'=>1223,'kode_kota'=>'1223','nama_kota'=>'KABUPATEN LABUHAN BATU UTARA','id_provinsi'=>12],
                ['id'=>1224,'kode_kota'=>'1224','nama_kota'=>'KABUPATEN NIAS UTARA','id_provinsi'=>12],
                ['id'=>1225,'kode_kota'=>'1225','nama_kota'=>'KABUPATEN NIAS BARAT','id_provinsi'=>12],
                ['id'=>1271,'kode_kota'=>'1271','nama_kota'=>'KOTA SIBOLGA','id_provinsi'=>12],
                ['id'=>1272,'kode_kota'=>'1272','nama_kota'=>'KOTA TANJUNG BALAI','id_provinsi'=>12],
                ['id'=>1273,'kode_kota'=>'1273','nama_kota'=>'KOTA PEMATANG SIANTAR','id_provinsi'=>12],
                ['id'=>1274,'kode_kota'=>'1274','nama_kota'=>'KOTA TEBING TINGGI','id_provinsi'=>12],
                ['id'=>1275,'kode_kota'=>'1275','nama_kota'=>'KOTA MEDAN','id_provinsi'=>12],
                ['id'=>1276,'kode_kota'=>'1276','nama_kota'=>'KOTA BINJAI','id_provinsi'=>12],
                ['id'=>1277,'kode_kota'=>'1277','nama_kota'=>'KOTA PADANGSIDIMPUAN','id_provinsi'=>12],
                ['id'=>1278,'kode_kota'=>'1278','nama_kota'=>'KOTA GUNUNGSITOLI','id_provinsi'=>12],
                ['id'=>1301,'kode_kota'=>'1301','nama_kota'=>'KABUPATEN KEPULAUAN MENTAWAI','id_provinsi'=>13],
                ['id'=>1302,'kode_kota'=>'1302','nama_kota'=>'KABUPATEN PESISIR SELATAN','id_provinsi'=>13],
                ['id'=>1303,'kode_kota'=>'1303','nama_kota'=>'KABUPATEN SOLOK','id_provinsi'=>13],
                ['id'=>1304,'kode_kota'=>'1304','nama_kota'=>'KABUPATEN SIJUNJUNG','id_provinsi'=>13],
                ['id'=>1305,'kode_kota'=>'1305','nama_kota'=>'KABUPATEN TANAH DATAR','id_provinsi'=>13],
                ['id'=>1306,'kode_kota'=>'1306','nama_kota'=>'KABUPATEN PADANG PARIAMAN','id_provinsi'=>13],
                ['id'=>1307,'kode_kota'=>'1307','nama_kota'=>'KABUPATEN AGAM','id_provinsi'=>13],
                ['id'=>1308,'kode_kota'=>'1308','nama_kota'=>'KABUPATEN LIMA PULUH KOTA','id_provinsi'=>13],
                ['id'=>1309,'kode_kota'=>'1309','nama_kota'=>'KABUPATEN PASAMAN','id_provinsi'=>13],
                ['id'=>1310,'kode_kota'=>'1310','nama_kota'=>'KABUPATEN SOLOK SELATAN','id_provinsi'=>13],
                ['id'=>1311,'kode_kota'=>'1311','nama_kota'=>'KABUPATEN DHARMASRAYA','id_provinsi'=>13],
                ['id'=>1312,'kode_kota'=>'1312','nama_kota'=>'KABUPATEN PASAMAN BARAT','id_provinsi'=>13],
                ['id'=>1371,'kode_kota'=>'1371','nama_kota'=>'KOTA PADANG','id_provinsi'=>13],
                ['id'=>1372,'kode_kota'=>'1372','nama_kota'=>'KOTA SOLOK','id_provinsi'=>13],
                ['id'=>1373,'kode_kota'=>'1373','nama_kota'=>'KOTA SAWAH LUNTO','id_provinsi'=>13],
                ['id'=>1374,'kode_kota'=>'1374','nama_kota'=>'KOTA PADANG PANJANG','id_provinsi'=>13],
                ['id'=>1375,'kode_kota'=>'1375','nama_kota'=>'KOTA BUKITTINGGI','id_provinsi'=>13],
                ['id'=>1376,'kode_kota'=>'1376','nama_kota'=>'KOTA PAYAKUMBUH','id_provinsi'=>13],
                ['id'=>1377,'kode_kota'=>'1377','nama_kota'=>'KOTA PARIAMAN','id_provinsi'=>13],
                ['id'=>1401,'kode_kota'=>'1401','nama_kota'=>'KABUPATEN KUANTAN SINGINGI','id_provinsi'=>14],
                ['id'=>1402,'kode_kota'=>'1402','nama_kota'=>'KABUPATEN INDRAGIRI HULU','id_provinsi'=>14],
                ['id'=>1403,'kode_kota'=>'1403','nama_kota'=>'KABUPATEN INDRAGIRI HILIR','id_provinsi'=>14],
                ['id'=>1404,'kode_kota'=>'1404','nama_kota'=>'KABUPATEN PELALAWAN','id_provinsi'=>14],
                ['id'=>1405,'kode_kota'=>'1405','nama_kota'=>'KABUPATEN S I A K','id_provinsi'=>14],
                ['id'=>1406,'kode_kota'=>'1406','nama_kota'=>'KABUPATEN KAMPAR','id_provinsi'=>14],
                ['id'=>1407,'kode_kota'=>'1407','nama_kota'=>'KABUPATEN ROKAN HULU','id_provinsi'=>14],
                ['id'=>1408,'kode_kota'=>'1408','nama_kota'=>'KABUPATEN BENGKALIS','id_provinsi'=>14],
                ['id'=>1409,'kode_kota'=>'1409','nama_kota'=>'KABUPATEN ROKAN HILIR','id_provinsi'=>14],
                ['id'=>1410,'kode_kota'=>'1410','nama_kota'=>'KABUPATEN KEPULAUAN MERANTI','id_provinsi'=>14],
                ['id'=>1471,'kode_kota'=>'1471','nama_kota'=>'KOTA PEKANBARU','id_provinsi'=>14],
                ['id'=>1473,'kode_kota'=>'1473','nama_kota'=>'KOTA D U M A I','id_provinsi'=>14],
                ['id'=>1501,'kode_kota'=>'1501','nama_kota'=>'KABUPATEN KERINCI','id_provinsi'=>15],
                ['id'=>1502,'kode_kota'=>'1502','nama_kota'=>'KABUPATEN MERANGIN','id_provinsi'=>15],
                ['id'=>1503,'kode_kota'=>'1503','nama_kota'=>'KABUPATEN SAROLANGUN','id_provinsi'=>15],
                ['id'=>1504,'kode_kota'=>'1504','nama_kota'=>'KABUPATEN BATANG HARI','id_provinsi'=>15],
                ['id'=>1505,'kode_kota'=>'1505','nama_kota'=>'KABUPATEN MUARO JAMBI','id_provinsi'=>15],
                ['id'=>1506,'kode_kota'=>'1506','nama_kota'=>'KABUPATEN TANJUNG JABUNG TIMUR','id_provinsi'=>15],
                ['id'=>1507,'kode_kota'=>'1507','nama_kota'=>'KABUPATEN TANJUNG JABUNG BARAT','id_provinsi'=>15],
                ['id'=>1508,'kode_kota'=>'1508','nama_kota'=>'KABUPATEN TEBO','id_provinsi'=>15],
                ['id'=>1509,'kode_kota'=>'1509','nama_kota'=>'KABUPATEN BUNGO','id_provinsi'=>15],
                ['id'=>1571,'kode_kota'=>'1571','nama_kota'=>'KOTA JAMBI','id_provinsi'=>15],
                ['id'=>1572,'kode_kota'=>'1572','nama_kota'=>'KOTA SUNGAI PENUH','id_provinsi'=>15],
                ['id'=>1601,'kode_kota'=>'1601','nama_kota'=>'KABUPATEN OGAN KOMERING ULU','id_provinsi'=>16],
                ['id'=>1602,'kode_kota'=>'1602','nama_kota'=>'KABUPATEN OGAN KOMERING ILIR','id_provinsi'=>16],
                ['id'=>1603,'kode_kota'=>'1603','nama_kota'=>'KABUPATEN MUARA ENIM','id_provinsi'=>16],
                ['id'=>1604,'kode_kota'=>'1604','nama_kota'=>'KABUPATEN LAHAT','id_provinsi'=>16],
                ['id'=>1605,'kode_kota'=>'1605','nama_kota'=>'KABUPATEN MUSI RAWAS','id_provinsi'=>16],
                ['id'=>1606,'kode_kota'=>'1606','nama_kota'=>'KABUPATEN MUSI BANYUASIN','id_provinsi'=>16],
                ['id'=>1607,'kode_kota'=>'1607','nama_kota'=>'KABUPATEN BANYU ASIN','id_provinsi'=>16],
                ['id'=>1608,'kode_kota'=>'1608','nama_kota'=>'KABUPATEN OGAN KOMERING ULU SELATAN','id_provinsi'=>16],
                ['id'=>1609,'kode_kota'=>'1609','nama_kota'=>'KABUPATEN OGAN KOMERING ULU TIMUR','id_provinsi'=>16],
                ['id'=>1610,'kode_kota'=>'1610','nama_kota'=>'KABUPATEN OGAN ILIR','id_provinsi'=>16],
                ['id'=>1611,'kode_kota'=>'1611','nama_kota'=>'KABUPATEN EMPAT LAWANG','id_provinsi'=>16],
                ['id'=>1612,'kode_kota'=>'1612','nama_kota'=>'KABUPATEN PENUKAL ABAB LEMATANG ILIR','id_provinsi'=>16],
                ['id'=>1613,'kode_kota'=>'1613','nama_kota'=>'KABUPATEN MUSI RAWAS UTARA','id_provinsi'=>16],
                ['id'=>1671,'kode_kota'=>'1671','nama_kota'=>'KOTA PALEMBANG','id_provinsi'=>16],
                ['id'=>1672,'kode_kota'=>'1672','nama_kota'=>'KOTA PRABUMULIH','id_provinsi'=>16],
                ['id'=>1673,'kode_kota'=>'1673','nama_kota'=>'KOTA PAGAR ALAM','id_provinsi'=>16],
                ['id'=>1674,'kode_kota'=>'1674','nama_kota'=>'KOTA LUBUKLINGGAU','id_provinsi'=>16],
                ['id'=>1701,'kode_kota'=>'1701','nama_kota'=>'KABUPATEN BENGKULU SELATAN','id_provinsi'=>17],
                ['id'=>1702,'kode_kota'=>'1702','nama_kota'=>'KABUPATEN REJANG LEBONG','id_provinsi'=>17],
                ['id'=>1703,'kode_kota'=>'1703','nama_kota'=>'KABUPATEN BENGKULU UTARA','id_provinsi'=>17],
                ['id'=>1704,'kode_kota'=>'1704','nama_kota'=>'KABUPATEN KAUR','id_provinsi'=>17],
                ['id'=>1705,'kode_kota'=>'1705','nama_kota'=>'KABUPATEN SELUMA','id_provinsi'=>17],
                ['id'=>1706,'kode_kota'=>'1706','nama_kota'=>'KABUPATEN MUKOMUKO','id_provinsi'=>17],
                ['id'=>1707,'kode_kota'=>'1707','nama_kota'=>'KABUPATEN LEBONG','id_provinsi'=>17],
                ['id'=>1708,'kode_kota'=>'1708','nama_kota'=>'KABUPATEN KEPAHIANG','id_provinsi'=>17],
                ['id'=>1709,'kode_kota'=>'1709','nama_kota'=>'KABUPATEN BENGKULU TENGAH','id_provinsi'=>17],
                ['id'=>1771,'kode_kota'=>'1771','nama_kota'=>'KOTA BENGKULU','id_provinsi'=>17],
                ['id'=>1801,'kode_kota'=>'1801','nama_kota'=>'KABUPATEN LAMPUNG BARAT','id_provinsi'=>18],
                ['id'=>1802,'kode_kota'=>'1802','nama_kota'=>'KABUPATEN TANGGAMUS','id_provinsi'=>18],
                ['id'=>1803,'kode_kota'=>'1803','nama_kota'=>'KABUPATEN LAMPUNG SELATAN','id_provinsi'=>18],
                ['id'=>1804,'kode_kota'=>'1804','nama_kota'=>'KABUPATEN LAMPUNG TIMUR','id_provinsi'=>18],
                ['id'=>1805,'kode_kota'=>'1805','nama_kota'=>'KABUPATEN LAMPUNG TENGAH','id_provinsi'=>18],
                ['id'=>1806,'kode_kota'=>'1806','nama_kota'=>'KABUPATEN LAMPUNG UTARA','id_provinsi'=>18],
                ['id'=>1807,'kode_kota'=>'1807','nama_kota'=>'KABUPATEN WAY KANAN','id_provinsi'=>18],
                ['id'=>1808,'kode_kota'=>'1808','nama_kota'=>'KABUPATEN TULANGBAWANG','id_provinsi'=>18],
                ['id'=>1809,'kode_kota'=>'1809','nama_kota'=>'KABUPATEN PESAWARAN','id_provinsi'=>18],
                ['id'=>1810,'kode_kota'=>'1810','nama_kota'=>'KABUPATEN PRINGSEWU','id_provinsi'=>18],
                ['id'=>1811,'kode_kota'=>'1811','nama_kota'=>'KABUPATEN MESUJI','id_provinsi'=>18],
                ['id'=>1812,'kode_kota'=>'1812','nama_kota'=>'KABUPATEN TULANG BAWANG BARAT','id_provinsi'=>18],
                ['id'=>1813,'kode_kota'=>'1813','nama_kota'=>'KABUPATEN PESISIR BARAT','id_provinsi'=>18],
                ['id'=>1871,'kode_kota'=>'1871','nama_kota'=>'KOTA BANDAR LAMPUNG','id_provinsi'=>18],
                ['id'=>1872,'kode_kota'=>'1872','nama_kota'=>'KOTA METRO','id_provinsi'=>18],
                ['id'=>1901,'kode_kota'=>'1901','nama_kota'=>'KABUPATEN BANGKA','id_provinsi'=>19],
                ['id'=>1902,'kode_kota'=>'1902','nama_kota'=>'KABUPATEN BELITUNG','id_provinsi'=>19],
                ['id'=>1903,'kode_kota'=>'1903','nama_kota'=>'KABUPATEN BANGKA BARAT','id_provinsi'=>19],
                ['id'=>1904,'kode_kota'=>'1904','nama_kota'=>'KABUPATEN BANGKA TENGAH','id_provinsi'=>19],
                ['id'=>1905,'kode_kota'=>'1905','nama_kota'=>'KABUPATEN BANGKA SELATAN','id_provinsi'=>19],
                ['id'=>1906,'kode_kota'=>'1906','nama_kota'=>'KABUPATEN BELITUNG TIMUR','id_provinsi'=>19],
                ['id'=>1971,'kode_kota'=>'1971','nama_kota'=>'KOTA PANGKAL PINANG','id_provinsi'=>19],
                ['id'=>2101,'kode_kota'=>'2101','nama_kota'=>'KABUPATEN KARIMUN','id_provinsi'=>21],
                ['id'=>2102,'kode_kota'=>'2102','nama_kota'=>'KABUPATEN BINTAN','id_provinsi'=>21],
                ['id'=>2103,'kode_kota'=>'2103','nama_kota'=>'KABUPATEN NATUNA','id_provinsi'=>21],
                ['id'=>2104,'kode_kota'=>'2104','nama_kota'=>'KABUPATEN LINGGA','id_provinsi'=>21],
                ['id'=>2105,'kode_kota'=>'2105','nama_kota'=>'KABUPATEN KEPULAUAN ANAMBAS','id_provinsi'=>21],
                ['id'=>2171,'kode_kota'=>'2171','nama_kota'=>'KOTA BATAM','id_provinsi'=>21],
                ['id'=>2172,'kode_kota'=>'2172','nama_kota'=>'KOTA TANJUNG PINANG','id_provinsi'=>21],
                ['id'=>3101,'kode_kota'=>'3101','nama_kota'=>'KABUPATEN KEPULAUAN SERIBU','id_provinsi'=>31],
                ['id'=>3171,'kode_kota'=>'3171','nama_kota'=>'KOTA JAKARTA SELATAN','id_provinsi'=>31],
                ['id'=>3172,'kode_kota'=>'3172','nama_kota'=>'KOTA JAKARTA TIMUR','id_provinsi'=>31],
                ['id'=>3173,'kode_kota'=>'3173','nama_kota'=>'KOTA JAKARTA PUSAT','id_provinsi'=>31],
                ['id'=>3174,'kode_kota'=>'3174','nama_kota'=>'KOTA JAKARTA BARAT','id_provinsi'=>31],
                ['id'=>3175,'kode_kota'=>'3175','nama_kota'=>'KOTA JAKARTA UTARA','id_provinsi'=>31],
                ['id'=>3201,'kode_kota'=>'3201','nama_kota'=>'KABUPATEN BOGOR','id_provinsi'=>32],
                ['id'=>3202,'kode_kota'=>'3202','nama_kota'=>'KABUPATEN SUKABUMI','id_provinsi'=>32],
                ['id'=>3203,'kode_kota'=>'3203','nama_kota'=>'KABUPATEN CIANJUR','id_provinsi'=>32],
                ['id'=>3204,'kode_kota'=>'3204','nama_kota'=>'KABUPATEN BANDUNG','id_provinsi'=>32],
                ['id'=>3205,'kode_kota'=>'3205','nama_kota'=>'KABUPATEN GARUT','id_provinsi'=>32],
                ['id'=>3206,'kode_kota'=>'3206','nama_kota'=>'KABUPATEN TASIKMALAYA','id_provinsi'=>32],
                ['id'=>3207,'kode_kota'=>'3207','nama_kota'=>'KABUPATEN CIAMIS','id_provinsi'=>32],
                ['id'=>3208,'kode_kota'=>'3208','nama_kota'=>'KABUPATEN KUNINGAN','id_provinsi'=>32],
                ['id'=>3209,'kode_kota'=>'3209','nama_kota'=>'KABUPATEN CIREBON','id_provinsi'=>32],
                ['id'=>3210,'kode_kota'=>'3210','nama_kota'=>'KABUPATEN MAJALENGKA','id_provinsi'=>32],
                ['id'=>3211,'kode_kota'=>'3211','nama_kota'=>'KABUPATEN SUMEDANG','id_provinsi'=>32],
                ['id'=>3212,'kode_kota'=>'3212','nama_kota'=>'KABUPATEN INDRAMAYU','id_provinsi'=>32],
                ['id'=>3213,'kode_kota'=>'3213','nama_kota'=>'KABUPATEN SUBANG','id_provinsi'=>32],
                ['id'=>3214,'kode_kota'=>'3214','nama_kota'=>'KABUPATEN PURWAKARTA','id_provinsi'=>32],
                ['id'=>3215,'kode_kota'=>'3215','nama_kota'=>'KABUPATEN KARAWANG','id_provinsi'=>32],
                ['id'=>3216,'kode_kota'=>'3216','nama_kota'=>'KABUPATEN BEKASI','id_provinsi'=>32],
                ['id'=>3217,'kode_kota'=>'3217','nama_kota'=>'KABUPATEN BANDUNG BARAT','id_provinsi'=>32],
                ['id'=>3218,'kode_kota'=>'3218','nama_kota'=>'KABUPATEN PANGANDARAN','id_provinsi'=>32],
                ['id'=>3271,'kode_kota'=>'3271','nama_kota'=>'KOTA BOGOR','id_provinsi'=>32],
                ['id'=>3272,'kode_kota'=>'3272','nama_kota'=>'KOTA SUKABUMI','id_provinsi'=>32],
                ['id'=>3273,'kode_kota'=>'3273','nama_kota'=>'KOTA BANDUNG','id_provinsi'=>32],
                ['id'=>3274,'kode_kota'=>'3274','nama_kota'=>'KOTA CIREBON','id_provinsi'=>32],
                ['id'=>3275,'kode_kota'=>'3275','nama_kota'=>'KOTA BEKASI','id_provinsi'=>32],
                ['id'=>3276,'kode_kota'=>'3276','nama_kota'=>'KOTA DEPOK','id_provinsi'=>32],
                ['id'=>3277,'kode_kota'=>'3277','nama_kota'=>'KOTA CIMAHI','id_provinsi'=>32],
                ['id'=>3278,'kode_kota'=>'3278','nama_kota'=>'KOTA TASIKMALAYA','id_provinsi'=>32],
                ['id'=>3279,'kode_kota'=>'3279','nama_kota'=>'KOTA BANJAR','id_provinsi'=>32],
                ['id'=>3301,'kode_kota'=>'3301','nama_kota'=>'KABUPATEN CILACAP','id_provinsi'=>33],
                ['id'=>3302,'kode_kota'=>'3302','nama_kota'=>'KABUPATEN BANYUMAS','id_provinsi'=>33],
                ['id'=>3303,'kode_kota'=>'3303','nama_kota'=>'KABUPATEN PURBALINGGA','id_provinsi'=>33],
                ['id'=>3304,'kode_kota'=>'3304','nama_kota'=>'KABUPATEN BANJARNEGARA','id_provinsi'=>33],
                ['id'=>3305,'kode_kota'=>'3305','nama_kota'=>'KABUPATEN KEBUMEN','id_provinsi'=>33],
                ['id'=>3306,'kode_kota'=>'3306','nama_kota'=>'KABUPATEN PURWOREJO','id_provinsi'=>33],
                ['id'=>3307,'kode_kota'=>'3307','nama_kota'=>'KABUPATEN WONOSOBO','id_provinsi'=>33],
                ['id'=>3308,'kode_kota'=>'3308','nama_kota'=>'KABUPATEN MAGELANG','id_provinsi'=>33],
                ['id'=>3309,'kode_kota'=>'3309','nama_kota'=>'KABUPATEN BOYOLALI','id_provinsi'=>33],
                ['id'=>3310,'kode_kota'=>'3310','nama_kota'=>'KABUPATEN KLATEN','id_provinsi'=>33],
                ['id'=>3311,'kode_kota'=>'3311','nama_kota'=>'KABUPATEN SUKOHARJO','id_provinsi'=>33],
                ['id'=>3312,'kode_kota'=>'3312','nama_kota'=>'KABUPATEN WONOGIRI','id_provinsi'=>33],
                ['id'=>3313,'kode_kota'=>'3313','nama_kota'=>'KABUPATEN KARANGANYAR','id_provinsi'=>33],
                ['id'=>3314,'kode_kota'=>'3314','nama_kota'=>'KABUPATEN SRAGEN','id_provinsi'=>33],
                ['id'=>3315,'kode_kota'=>'3315','nama_kota'=>'KABUPATEN GROBOGAN','id_provinsi'=>33],
                ['id'=>3316,'kode_kota'=>'3316','nama_kota'=>'KABUPATEN BLORA','id_provinsi'=>33],
                ['id'=>3317,'kode_kota'=>'3317','nama_kota'=>'KABUPATEN REMBANG','id_provinsi'=>33],
                ['id'=>3318,'kode_kota'=>'3318','nama_kota'=>'KABUPATEN PATI','id_provinsi'=>33],
                ['id'=>3319,'kode_kota'=>'3319','nama_kota'=>'KABUPATEN KUDUS','id_provinsi'=>33],
                ['id'=>3320,'kode_kota'=>'3320','nama_kota'=>'KABUPATEN JEPARA','id_provinsi'=>33],
                ['id'=>3321,'kode_kota'=>'3321','nama_kota'=>'KABUPATEN DEMAK','id_provinsi'=>33],
                ['id'=>3322,'kode_kota'=>'3322','nama_kota'=>'KABUPATEN SEMARANG','id_provinsi'=>33],
                ['id'=>3323,'kode_kota'=>'3323','nama_kota'=>'KABUPATEN TEMANGGUNG','id_provinsi'=>33],
                ['id'=>3324,'kode_kota'=>'3324','nama_kota'=>'KABUPATEN KENDAL','id_provinsi'=>33],
                ['id'=>3325,'kode_kota'=>'3325','nama_kota'=>'KABUPATEN BATANG','id_provinsi'=>33],
                ['id'=>3326,'kode_kota'=>'3326','nama_kota'=>'KABUPATEN PEKALONGAN','id_provinsi'=>33],
                ['id'=>3327,'kode_kota'=>'3327','nama_kota'=>'KABUPATEN PEMALANG','id_provinsi'=>33],
                ['id'=>3328,'kode_kota'=>'3328','nama_kota'=>'KABUPATEN TEGAL','id_provinsi'=>33],
                ['id'=>3329,'kode_kota'=>'3329','nama_kota'=>'KABUPATEN BREBES','id_provinsi'=>33],
                ['id'=>3371,'kode_kota'=>'3371','nama_kota'=>'KOTA MAGELANG','id_provinsi'=>33],
                ['id'=>3372,'kode_kota'=>'3372','nama_kota'=>'KOTA SURAKARTA','id_provinsi'=>33],
                ['id'=>3373,'kode_kota'=>'3373','nama_kota'=>'KOTA SALATIGA','id_provinsi'=>33],
                ['id'=>3374,'kode_kota'=>'3374','nama_kota'=>'KOTA SEMARANG','id_provinsi'=>33],
                ['id'=>3375,'kode_kota'=>'3375','nama_kota'=>'KOTA PEKALONGAN','id_provinsi'=>33],
                ['id'=>3376,'kode_kota'=>'3376','nama_kota'=>'KOTA TEGAL','id_provinsi'=>33],
                ['id'=>3401,'kode_kota'=>'3401','nama_kota'=>'KABUPATEN KULON PROGO','id_provinsi'=>34],
                ['id'=>3402,'kode_kota'=>'3402','nama_kota'=>'KABUPATEN BANTUL','id_provinsi'=>34],
                ['id'=>3403,'kode_kota'=>'3403','nama_kota'=>'KABUPATEN GUNUNG KIDUL','id_provinsi'=>34],
                ['id'=>3404,'kode_kota'=>'3404','nama_kota'=>'KABUPATEN SLEMAN','id_provinsi'=>34],
                ['id'=>3471,'kode_kota'=>'3471','nama_kota'=>'KOTA YOGYAKARTA','id_provinsi'=>34],
                ['id'=>3501,'kode_kota'=>'3501','nama_kota'=>'KABUPATEN PACITAN','id_provinsi'=>35],
                ['id'=>3502,'kode_kota'=>'3502','nama_kota'=>'KABUPATEN PONOROGO','id_provinsi'=>35],
                ['id'=>3503,'kode_kota'=>'3503','nama_kota'=>'KABUPATEN TRENGGALEK','id_provinsi'=>35],
                ['id'=>3504,'kode_kota'=>'3504','nama_kota'=>'KABUPATEN TULUNGAGUNG','id_provinsi'=>35],
                ['id'=>3505,'kode_kota'=>'3505','nama_kota'=>'KABUPATEN BLITAR','id_provinsi'=>35],
                ['id'=>3506,'kode_kota'=>'3506','nama_kota'=>'KABUPATEN KEDIRI','id_provinsi'=>35],
                ['id'=>3507,'kode_kota'=>'3507','nama_kota'=>'KABUPATEN MALANG','id_provinsi'=>35],
                ['id'=>3508,'kode_kota'=>'3508','nama_kota'=>'KABUPATEN LUMAJANG','id_provinsi'=>35],
                ['id'=>3509,'kode_kota'=>'3509','nama_kota'=>'KABUPATEN JEMBER','id_provinsi'=>35],
                ['id'=>3510,'kode_kota'=>'3510','nama_kota'=>'KABUPATEN BANYUWANGI','id_provinsi'=>35],
                ['id'=>3511,'kode_kota'=>'3511','nama_kota'=>'KABUPATEN BONDOWOSO','id_provinsi'=>35],
                ['id'=>3512,'kode_kota'=>'3512','nama_kota'=>'KABUPATEN SITUBONDO','id_provinsi'=>35],
                ['id'=>3513,'kode_kota'=>'3513','nama_kota'=>'KABUPATEN PROBOLINGGO','id_provinsi'=>35],
                ['id'=>3514,'kode_kota'=>'3514','nama_kota'=>'KABUPATEN PASURUAN','id_provinsi'=>35],
                ['id'=>3515,'kode_kota'=>'3515','nama_kota'=>'KABUPATEN SIDOARJO','id_provinsi'=>35],
                ['id'=>3516,'kode_kota'=>'3516','nama_kota'=>'KABUPATEN MOJOKERTO','id_provinsi'=>35],
                ['id'=>3517,'kode_kota'=>'3517','nama_kota'=>'KABUPATEN JOMBANG','id_provinsi'=>35],
                ['id'=>3518,'kode_kota'=>'3518','nama_kota'=>'KABUPATEN NGANJUK','id_provinsi'=>35],
                ['id'=>3519,'kode_kota'=>'3519','nama_kota'=>'KABUPATEN MADIUN','id_provinsi'=>35],
                ['id'=>3520,'kode_kota'=>'3520','nama_kota'=>'KABUPATEN MAGETAN','id_provinsi'=>35],
                ['id'=>3521,'kode_kota'=>'3521','nama_kota'=>'KABUPATEN NGAWI','id_provinsi'=>35],
                ['id'=>3522,'kode_kota'=>'3522','nama_kota'=>'KABUPATEN BOJONEGORO','id_provinsi'=>35],
                ['id'=>3523,'kode_kota'=>'3523','nama_kota'=>'KABUPATEN TUBAN','id_provinsi'=>35],
                ['id'=>3524,'kode_kota'=>'3524','nama_kota'=>'KABUPATEN LAMONGAN','id_provinsi'=>35],
                ['id'=>3525,'kode_kota'=>'3525','nama_kota'=>'KABUPATEN GRESIK','id_provinsi'=>35],
                ['id'=>3526,'kode_kota'=>'3526','nama_kota'=>'KABUPATEN BANGKALAN','id_provinsi'=>35],
                ['id'=>3527,'kode_kota'=>'3527','nama_kota'=>'KABUPATEN SAMPANG','id_provinsi'=>35],
                ['id'=>3528,'kode_kota'=>'3528','nama_kota'=>'KABUPATEN PAMEKASAN','id_provinsi'=>35],
                ['id'=>3529,'kode_kota'=>'3529','nama_kota'=>'KABUPATEN SUMENEP','id_provinsi'=>35],
                ['id'=>3571,'kode_kota'=>'3571','nama_kota'=>'KOTA KEDIRI','id_provinsi'=>35],
                ['id'=>3572,'kode_kota'=>'3572','nama_kota'=>'KOTA BLITAR','id_provinsi'=>35],
                ['id'=>3573,'kode_kota'=>'3573','nama_kota'=>'KOTA MALANG','id_provinsi'=>35],
                ['id'=>3574,'kode_kota'=>'3574','nama_kota'=>'KOTA PROBOLINGGO','id_provinsi'=>35],
                ['id'=>3575,'kode_kota'=>'3575','nama_kota'=>'KOTA PASURUAN','id_provinsi'=>35],
                ['id'=>3576,'kode_kota'=>'3576','nama_kota'=>'KOTA MOJOKERTO','id_provinsi'=>35],
                ['id'=>3577,'kode_kota'=>'3577','nama_kota'=>'KOTA MADIUN','id_provinsi'=>35],
                ['id'=>3578,'kode_kota'=>'3578','nama_kota'=>'KOTA SURABAYA','id_provinsi'=>35],
                ['id'=>3579,'kode_kota'=>'3579','nama_kota'=>'KOTA BATU','id_provinsi'=>35],
                ['id'=>3601,'kode_kota'=>'3601','nama_kota'=>'KABUPATEN PANDEGLANG','id_provinsi'=>36],
                ['id'=>3602,'kode_kota'=>'3602','nama_kota'=>'KABUPATEN LEBAK','id_provinsi'=>36],
                ['id'=>3603,'kode_kota'=>'3603','nama_kota'=>'KABUPATEN TANGERANG','id_provinsi'=>36],
                ['id'=>3604,'kode_kota'=>'3604','nama_kota'=>'KABUPATEN SERANG','id_provinsi'=>36],
                ['id'=>3671,'kode_kota'=>'3671','nama_kota'=>'KOTA TANGERANG','id_provinsi'=>36],
                ['id'=>3672,'kode_kota'=>'3672','nama_kota'=>'KOTA CILEGON','id_provinsi'=>36],
                ['id'=>3673,'kode_kota'=>'3673','nama_kota'=>'KOTA SERANG','id_provinsi'=>36],
                ['id'=>3674,'kode_kota'=>'3674','nama_kota'=>'KOTA TANGERANG SELATAN','id_provinsi'=>36],
                ['id'=>5101,'kode_kota'=>'5101','nama_kota'=>'KABUPATEN JEMBRANA','id_provinsi'=>51],
                ['id'=>5102,'kode_kota'=>'5102','nama_kota'=>'KABUPATEN TABANAN','id_provinsi'=>51],
                ['id'=>5103,'kode_kota'=>'5103','nama_kota'=>'KABUPATEN BADUNG','id_provinsi'=>51],
                ['id'=>5104,'kode_kota'=>'5104','nama_kota'=>'KABUPATEN GIANYAR','id_provinsi'=>51],
                ['id'=>5105,'kode_kota'=>'5105','nama_kota'=>'KABUPATEN KLUNGKUNG','id_provinsi'=>51],
                ['id'=>5106,'kode_kota'=>'5106','nama_kota'=>'KABUPATEN BANGLI','id_provinsi'=>51],
                ['id'=>5107,'kode_kota'=>'5107','nama_kota'=>'KABUPATEN KARANG ASEM','id_provinsi'=>51],
                ['id'=>5108,'kode_kota'=>'5108','nama_kota'=>'KABUPATEN BULELENG','id_provinsi'=>51],
                ['id'=>5171,'kode_kota'=>'5171','nama_kota'=>'KOTA DENPASAR','id_provinsi'=>51],
                ['id'=>5201,'kode_kota'=>'5201','nama_kota'=>'KABUPATEN LOMBOK BARAT','id_provinsi'=>52],
                ['id'=>5202,'kode_kota'=>'5202','nama_kota'=>'KABUPATEN LOMBOK TENGAH','id_provinsi'=>52],
                ['id'=>5203,'kode_kota'=>'5203','nama_kota'=>'KABUPATEN LOMBOK TIMUR','id_provinsi'=>52],
                ['id'=>5204,'kode_kota'=>'5204','nama_kota'=>'KABUPATEN SUMBAWA','id_provinsi'=>52],
                ['id'=>5205,'kode_kota'=>'5205','nama_kota'=>'KABUPATEN DOMPU','id_provinsi'=>52],
                ['id'=>5206,'kode_kota'=>'5206','nama_kota'=>'KABUPATEN BIMA','id_provinsi'=>52],
                ['id'=>5207,'kode_kota'=>'5207','nama_kota'=>'KABUPATEN SUMBAWA BARAT','id_provinsi'=>52],
                ['id'=>5208,'kode_kota'=>'5208','nama_kota'=>'KABUPATEN LOMBOK UTARA','id_provinsi'=>52],
                ['id'=>5271,'kode_kota'=>'5271','nama_kota'=>'KOTA MATARAM','id_provinsi'=>52],
                ['id'=>5272,'kode_kota'=>'5272','nama_kota'=>'KOTA BIMA','id_provinsi'=>52],
                ['id'=>5301,'kode_kota'=>'5301','nama_kota'=>'KABUPATEN SUMBA BARAT','id_provinsi'=>53],
                ['id'=>5302,'kode_kota'=>'5302','nama_kota'=>'KABUPATEN SUMBA TIMUR','id_provinsi'=>53],
                ['id'=>5303,'kode_kota'=>'5303','nama_kota'=>'KABUPATEN KUPANG','id_provinsi'=>53],
                ['id'=>5304,'kode_kota'=>'5304','nama_kota'=>'KABUPATEN TIMOR TENGAH SELATAN','id_provinsi'=>53],
                ['id'=>5305,'kode_kota'=>'5305','nama_kota'=>'KABUPATEN TIMOR TENGAH UTARA','id_provinsi'=>53],
                ['id'=>5306,'kode_kota'=>'5306','nama_kota'=>'KABUPATEN BELU','id_provinsi'=>53],
                ['id'=>5307,'kode_kota'=>'5307','nama_kota'=>'KABUPATEN ALOR','id_provinsi'=>53],
                ['id'=>5308,'kode_kota'=>'5308','nama_kota'=>'KABUPATEN LEMBATA','id_provinsi'=>53],
                ['id'=>5309,'kode_kota'=>'5309','nama_kota'=>'KABUPATEN FLORES TIMUR','id_provinsi'=>53],
                ['id'=>5310,'kode_kota'=>'5310','nama_kota'=>'KABUPATEN SIKKA','id_provinsi'=>53],
                ['id'=>5311,'kode_kota'=>'5311','nama_kota'=>'KABUPATEN ENDE','id_provinsi'=>53],
                ['id'=>5312,'kode_kota'=>'5312','nama_kota'=>'KABUPATEN NGADA','id_provinsi'=>53],
                ['id'=>5313,'kode_kota'=>'5313','nama_kota'=>'KABUPATEN MANGGARAI','id_provinsi'=>53],
                ['id'=>5314,'kode_kota'=>'5314','nama_kota'=>'KABUPATEN ROTE NDAO','id_provinsi'=>53],
                ['id'=>5315,'kode_kota'=>'5315','nama_kota'=>'KABUPATEN MANGGARAI BARAT','id_provinsi'=>53],
                ['id'=>5316,'kode_kota'=>'5316','nama_kota'=>'KABUPATEN SUMBA TENGAH','id_provinsi'=>53],
                ['id'=>5317,'kode_kota'=>'5317','nama_kota'=>'KABUPATEN SUMBA BARAT DAYA','id_provinsi'=>53],
                ['id'=>5318,'kode_kota'=>'5318','nama_kota'=>'KABUPATEN NAGEKEO','id_provinsi'=>53],
                ['id'=>5319,'kode_kota'=>'5319','nama_kota'=>'KABUPATEN MANGGARAI TIMUR','id_provinsi'=>53],
                ['id'=>5320,'kode_kota'=>'5320','nama_kota'=>'KABUPATEN SABU RAIJUA','id_provinsi'=>53],
                ['id'=>5321,'kode_kota'=>'5321','nama_kota'=>'KABUPATEN MALAKA','id_provinsi'=>53],
                ['id'=>5371,'kode_kota'=>'5371','nama_kota'=>'KOTA KUPANG','id_provinsi'=>53],
                ['id'=>6101,'kode_kota'=>'6101','nama_kota'=>'KABUPATEN SAMBAS','id_provinsi'=>61],
                ['id'=>6102,'kode_kota'=>'6102','nama_kota'=>'KABUPATEN BENGKAYANG','id_provinsi'=>61],
                ['id'=>6103,'kode_kota'=>'6103','nama_kota'=>'KABUPATEN LANDAK','id_provinsi'=>61],
                ['id'=>6104,'kode_kota'=>'6104','nama_kota'=>'KABUPATEN MEMPAWAH','id_provinsi'=>61],
                ['id'=>6105,'kode_kota'=>'6105','nama_kota'=>'KABUPATEN SANGGAU','id_provinsi'=>61],
                ['id'=>6106,'kode_kota'=>'6106','nama_kota'=>'KABUPATEN KETAPANG','id_provinsi'=>61],
                ['id'=>6107,'kode_kota'=>'6107','nama_kota'=>'KABUPATEN SINTANG','id_provinsi'=>61],
                ['id'=>6108,'kode_kota'=>'6108','nama_kota'=>'KABUPATEN KAPUAS HULU','id_provinsi'=>61],
                ['id'=>6109,'kode_kota'=>'6109','nama_kota'=>'KABUPATEN SEKADAU','id_provinsi'=>61],
                ['id'=>6110,'kode_kota'=>'6110','nama_kota'=>'KABUPATEN MELAWI','id_provinsi'=>61],
                ['id'=>6111,'kode_kota'=>'6111','nama_kota'=>'KABUPATEN KAYONG UTARA','id_provinsi'=>61],
                ['id'=>6112,'kode_kota'=>'6112','nama_kota'=>'KABUPATEN KUBU RAYA','id_provinsi'=>61],
                ['id'=>6171,'kode_kota'=>'6171','nama_kota'=>'KOTA PONTIANAK','id_provinsi'=>61],
                ['id'=>6172,'kode_kota'=>'6172','nama_kota'=>'KOTA SINGKAWANG','id_provinsi'=>61],
                ['id'=>6201,'kode_kota'=>'6201','nama_kota'=>'KABUPATEN KOTAWARINGIN BARAT','id_provinsi'=>62],
                ['id'=>6202,'kode_kota'=>'6202','nama_kota'=>'KABUPATEN KOTAWARINGIN TIMUR','id_provinsi'=>62],
                ['id'=>6203,'kode_kota'=>'6203','nama_kota'=>'KABUPATEN KAPUAS','id_provinsi'=>62],
                ['id'=>6204,'kode_kota'=>'6204','nama_kota'=>'KABUPATEN BARITO SELATAN','id_provinsi'=>62],
                ['id'=>6205,'kode_kota'=>'6205','nama_kota'=>'KABUPATEN BARITO UTARA','id_provinsi'=>62],
                ['id'=>6206,'kode_kota'=>'6206','nama_kota'=>'KABUPATEN SUKAMARA','id_provinsi'=>62],
                ['id'=>6207,'kode_kota'=>'6207','nama_kota'=>'KABUPATEN LAMANDAU','id_provinsi'=>62],
                ['id'=>6208,'kode_kota'=>'6208','nama_kota'=>'KABUPATEN SERUYAN','id_provinsi'=>62],
                ['id'=>6209,'kode_kota'=>'6209','nama_kota'=>'KABUPATEN KATINGAN','id_provinsi'=>62],
                ['id'=>6210,'kode_kota'=>'6210','nama_kota'=>'KABUPATEN PULANG PISAU','id_provinsi'=>62],
                ['id'=>6211,'kode_kota'=>'6211','nama_kota'=>'KABUPATEN GUNUNG MAS','id_provinsi'=>62],
                ['id'=>6212,'kode_kota'=>'6212','nama_kota'=>'KABUPATEN BARITO TIMUR','id_provinsi'=>62],
                ['id'=>6213,'kode_kota'=>'6213','nama_kota'=>'KABUPATEN MURUNG RAYA','id_provinsi'=>62],
                ['id'=>6271,'kode_kota'=>'6271','nama_kota'=>'KOTA PALANGKA RAYA','id_provinsi'=>62],
                ['id'=>6301,'kode_kota'=>'6301','nama_kota'=>'KABUPATEN TANAH LAUT','id_provinsi'=>63],
                ['id'=>6302,'kode_kota'=>'6302','nama_kota'=>'KABUPATEN KOTA BARU','id_provinsi'=>63],
                ['id'=>6303,'kode_kota'=>'6303','nama_kota'=>'KABUPATEN BANJAR','id_provinsi'=>63],
                ['id'=>6304,'kode_kota'=>'6304','nama_kota'=>'KABUPATEN BARITO KUALA','id_provinsi'=>63],
                ['id'=>6305,'kode_kota'=>'6305','nama_kota'=>'KABUPATEN TAPIN','id_provinsi'=>63],
                ['id'=>6306,'kode_kota'=>'6306','nama_kota'=>'KABUPATEN HULU SUNGAI SELATAN','id_provinsi'=>63],
                ['id'=>6307,'kode_kota'=>'6307','nama_kota'=>'KABUPATEN HULU SUNGAI TENGAH','id_provinsi'=>63],
                ['id'=>6308,'kode_kota'=>'6308','nama_kota'=>'KABUPATEN HULU SUNGAI UTARA','id_provinsi'=>63],
                ['id'=>6309,'kode_kota'=>'6309','nama_kota'=>'KABUPATEN TABALONG','id_provinsi'=>63],
                ['id'=>6310,'kode_kota'=>'6310','nama_kota'=>'KABUPATEN TANAH BUMBU','id_provinsi'=>63],
                ['id'=>6311,'kode_kota'=>'6311','nama_kota'=>'KABUPATEN BALANGAN','id_provinsi'=>63],
                ['id'=>6371,'kode_kota'=>'6371','nama_kota'=>'KOTA BANJARMASIN','id_provinsi'=>63],
                ['id'=>6372,'kode_kota'=>'6372','nama_kota'=>'KOTA BANJAR BARU','id_provinsi'=>63],
                ['id'=>6401,'kode_kota'=>'6401','nama_kota'=>'KABUPATEN PASER','id_provinsi'=>64],
                ['id'=>6402,'kode_kota'=>'6402','nama_kota'=>'KABUPATEN KUTAI BARAT','id_provinsi'=>64],
                ['id'=>6403,'kode_kota'=>'6403','nama_kota'=>'KABUPATEN KUTAI KARTANEGARA','id_provinsi'=>64],
                ['id'=>6404,'kode_kota'=>'6404','nama_kota'=>'KABUPATEN KUTAI TIMUR','id_provinsi'=>64],
                ['id'=>6405,'kode_kota'=>'6405','nama_kota'=>'KABUPATEN BERAU','id_provinsi'=>64],
                ['id'=>6409,'kode_kota'=>'6409','nama_kota'=>'KABUPATEN PENAJAM PASER UTARA','id_provinsi'=>64],
                ['id'=>6411,'kode_kota'=>'6411','nama_kota'=>'KABUPATEN MAHAKAM HULU','id_provinsi'=>64],
                ['id'=>6471,'kode_kota'=>'6471','nama_kota'=>'KOTA BALIKPAPAN','id_provinsi'=>64],
                ['id'=>6472,'kode_kota'=>'6472','nama_kota'=>'KOTA SAMARINDA','id_provinsi'=>64],
                ['id'=>6474,'kode_kota'=>'6474','nama_kota'=>'KOTA BONTANG','id_provinsi'=>64],
                ['id'=>6501,'kode_kota'=>'6501','nama_kota'=>'KABUPATEN MALINAU','id_provinsi'=>65],
                ['id'=>6502,'kode_kota'=>'6502','nama_kota'=>'KABUPATEN BULUNGAN','id_provinsi'=>65],
                ['id'=>6503,'kode_kota'=>'6503','nama_kota'=>'KABUPATEN TANA TIDUNG','id_provinsi'=>65],
                ['id'=>6504,'kode_kota'=>'6504','nama_kota'=>'KABUPATEN NUNUKAN','id_provinsi'=>65],
                ['id'=>6571,'kode_kota'=>'6571','nama_kota'=>'KOTA TARAKAN','id_provinsi'=>65],
                ['id'=>7101,'kode_kota'=>'7101','nama_kota'=>'KABUPATEN BOLAANG MONGONDOW','id_provinsi'=>71],
                ['id'=>7102,'kode_kota'=>'7102','nama_kota'=>'KABUPATEN MINAHASA','id_provinsi'=>71],
                ['id'=>7103,'kode_kota'=>'7103','nama_kota'=>'KABUPATEN KEPULAUAN SANGIHE','id_provinsi'=>71],
                ['id'=>7104,'kode_kota'=>'7104','nama_kota'=>'KABUPATEN KEPULAUAN TALAUD','id_provinsi'=>71],
                ['id'=>7105,'kode_kota'=>'7105','nama_kota'=>'KABUPATEN MINAHASA SELATAN','id_provinsi'=>71],
                ['id'=>7106,'kode_kota'=>'7106','nama_kota'=>'KABUPATEN MINAHASA UTARA','id_provinsi'=>71],
                ['id'=>7107,'kode_kota'=>'7107','nama_kota'=>'KABUPATEN BOLAANG MONGONDOW UTARA','id_provinsi'=>71],
                ['id'=>7108,'kode_kota'=>'7108','nama_kota'=>'KABUPATEN SIAU TAGULANDANG BIARO','id_provinsi'=>71],
                ['id'=>7109,'kode_kota'=>'7109','nama_kota'=>'KABUPATEN MINAHASA TENGGARA','id_provinsi'=>71],
                ['id'=>7110,'kode_kota'=>'7110','nama_kota'=>'KABUPATEN BOLAANG MONGONDOW SELATAN','id_provinsi'=>71],
                ['id'=>7111,'kode_kota'=>'7111','nama_kota'=>'KABUPATEN BOLAANG MONGONDOW TIMUR','id_provinsi'=>71],
                ['id'=>7171,'kode_kota'=>'7171','nama_kota'=>'KOTA MANADO','id_provinsi'=>71],
                ['id'=>7172,'kode_kota'=>'7172','nama_kota'=>'KOTA BITUNG','id_provinsi'=>71],
                ['id'=>7173,'kode_kota'=>'7173','nama_kota'=>'KOTA TOMOHON','id_provinsi'=>71],
                ['id'=>7174,'kode_kota'=>'7174','nama_kota'=>'KOTA KOTAMOBAGU','id_provinsi'=>71],
                ['id'=>7201,'kode_kota'=>'7201','nama_kota'=>'KABUPATEN BANGGAI KEPULAUAN','id_provinsi'=>72],
                ['id'=>7202,'kode_kota'=>'7202','nama_kota'=>'KABUPATEN BANGGAI','id_provinsi'=>72],
                ['id'=>7203,'kode_kota'=>'7203','nama_kota'=>'KABUPATEN MOROWALI','id_provinsi'=>72],
                ['id'=>7204,'kode_kota'=>'7204','nama_kota'=>'KABUPATEN POSO','id_provinsi'=>72],
                ['id'=>7205,'kode_kota'=>'7205','nama_kota'=>'KABUPATEN DONGGALA','id_provinsi'=>72],
                ['id'=>7206,'kode_kota'=>'7206','nama_kota'=>'KABUPATEN TOLI-TOLI','id_provinsi'=>72],
                ['id'=>7207,'kode_kota'=>'7207','nama_kota'=>'KABUPATEN BUOL','id_provinsi'=>72],
                ['id'=>7208,'kode_kota'=>'7208','nama_kota'=>'KABUPATEN PARIGI MOUTONG','id_provinsi'=>72],
                ['id'=>7209,'kode_kota'=>'7209','nama_kota'=>'KABUPATEN TOJO UNA-UNA','id_provinsi'=>72],
                ['id'=>7210,'kode_kota'=>'7210','nama_kota'=>'KABUPATEN SIGI','id_provinsi'=>72],
                ['id'=>7211,'kode_kota'=>'7211','nama_kota'=>'KABUPATEN BANGGAI LAUT','id_provinsi'=>72],
                ['id'=>7212,'kode_kota'=>'7212','nama_kota'=>'KABUPATEN MOROWALI UTARA','id_provinsi'=>72],
                ['id'=>7271,'kode_kota'=>'7271','nama_kota'=>'KOTA PALU','id_provinsi'=>72],
                ['id'=>7301,'kode_kota'=>'7301','nama_kota'=>'KABUPATEN KEPULAUAN SELAYAR','id_provinsi'=>73],
                ['id'=>7302,'kode_kota'=>'7302','nama_kota'=>'KABUPATEN BULUKUMBA','id_provinsi'=>73],
                ['id'=>7303,'kode_kota'=>'7303','nama_kota'=>'KABUPATEN BANTAENG','id_provinsi'=>73],
                ['id'=>7304,'kode_kota'=>'7304','nama_kota'=>'KABUPATEN JENEPONTO','id_provinsi'=>73],
                ['id'=>7305,'kode_kota'=>'7305','nama_kota'=>'KABUPATEN TAKALAR','id_provinsi'=>73],
                ['id'=>7306,'kode_kota'=>'7306','nama_kota'=>'KABUPATEN GOWA','id_provinsi'=>73],
                ['id'=>7307,'kode_kota'=>'7307','nama_kota'=>'KABUPATEN SINJAI','id_provinsi'=>73],
                ['id'=>7308,'kode_kota'=>'7308','nama_kota'=>'KABUPATEN MAROS','id_provinsi'=>73],
                ['id'=>7309,'kode_kota'=>'7309','nama_kota'=>'KABUPATEN PANGKAJENE DAN KEPULAUAN','id_provinsi'=>73],
                ['id'=>7310,'kode_kota'=>'7310','nama_kota'=>'KABUPATEN BARRU','id_provinsi'=>73],
                ['id'=>7311,'kode_kota'=>'7311','nama_kota'=>'KABUPATEN BONE','id_provinsi'=>73],
                ['id'=>7312,'kode_kota'=>'7312','nama_kota'=>'KABUPATEN SOPPENG','id_provinsi'=>73],
                ['id'=>7313,'kode_kota'=>'7313','nama_kota'=>'KABUPATEN WAJO','id_provinsi'=>73],
                ['id'=>7314,'kode_kota'=>'7314','nama_kota'=>'KABUPATEN SIDENRENG RAPPANG','id_provinsi'=>73],
                ['id'=>7315,'kode_kota'=>'7315','nama_kota'=>'KABUPATEN PINRANG','id_provinsi'=>73],
                ['id'=>7316,'kode_kota'=>'7316','nama_kota'=>'KABUPATEN ENREKANG','id_provinsi'=>73],
                ['id'=>7317,'kode_kota'=>'7317','nama_kota'=>'KABUPATEN LUWU','id_provinsi'=>73],
                ['id'=>7318,'kode_kota'=>'7318','nama_kota'=>'KABUPATEN TANA TORAJA','id_provinsi'=>73],
                ['id'=>7322,'kode_kota'=>'7322','nama_kota'=>'KABUPATEN LUWU UTARA','id_provinsi'=>73],
                ['id'=>7325,'kode_kota'=>'7325','nama_kota'=>'KABUPATEN LUWU TIMUR','id_provinsi'=>73],
                ['id'=>7326,'kode_kota'=>'7326','nama_kota'=>'KABUPATEN TORAJA UTARA','id_provinsi'=>73],
                ['id'=>7371,'kode_kota'=>'7371','nama_kota'=>'KOTA MAKASSAR','id_provinsi'=>73],
                ['id'=>7372,'kode_kota'=>'7372','nama_kota'=>'KOTA PAREPARE','id_provinsi'=>73],
                ['id'=>7373,'kode_kota'=>'7373','nama_kota'=>'KOTA PALOPO','id_provinsi'=>73],
                ['id'=>7401,'kode_kota'=>'7401','nama_kota'=>'KABUPATEN BUTON','id_provinsi'=>74],
                ['id'=>7402,'kode_kota'=>'7402','nama_kota'=>'KABUPATEN MUNA','id_provinsi'=>74],
                ['id'=>7403,'kode_kota'=>'7403','nama_kota'=>'KABUPATEN KONAWE','id_provinsi'=>74],
                ['id'=>7404,'kode_kota'=>'7404','nama_kota'=>'KABUPATEN KOLAKA','id_provinsi'=>74],
                ['id'=>7405,'kode_kota'=>'7405','nama_kota'=>'KABUPATEN KONAWE SELATAN','id_provinsi'=>74],
                ['id'=>7406,'kode_kota'=>'7406','nama_kota'=>'KABUPATEN BOMBANA','id_provinsi'=>74],
                ['id'=>7407,'kode_kota'=>'7407','nama_kota'=>'KABUPATEN WAKATOBI','id_provinsi'=>74],
                ['id'=>7408,'kode_kota'=>'7408','nama_kota'=>'KABUPATEN KOLAKA UTARA','id_provinsi'=>74],
                ['id'=>7409,'kode_kota'=>'7409','nama_kota'=>'KABUPATEN BUTON UTARA','id_provinsi'=>74],
                ['id'=>7410,'kode_kota'=>'7410','nama_kota'=>'KABUPATEN KONAWE UTARA','id_provinsi'=>74],
                ['id'=>7411,'kode_kota'=>'7411','nama_kota'=>'KABUPATEN KOLAKA TIMUR','id_provinsi'=>74],
                ['id'=>7412,'kode_kota'=>'7412','nama_kota'=>'KABUPATEN KONAWE KEPULAUAN','id_provinsi'=>74],
                ['id'=>7413,'kode_kota'=>'7413','nama_kota'=>'KABUPATEN MUNA BARAT','id_provinsi'=>74],
                ['id'=>7414,'kode_kota'=>'7414','nama_kota'=>'KABUPATEN BUTON TENGAH','id_provinsi'=>74],
                ['id'=>7415,'kode_kota'=>'7415','nama_kota'=>'KABUPATEN BUTON SELATAN','id_provinsi'=>74],
                ['id'=>7471,'kode_kota'=>'7471','nama_kota'=>'KOTA KENDARI','id_provinsi'=>74],
                ['id'=>7472,'kode_kota'=>'7472','nama_kota'=>'KOTA BAUBAU','id_provinsi'=>74],
                ['id'=>7501,'kode_kota'=>'7501','nama_kota'=>'KABUPATEN BOALEMO','id_provinsi'=>75],
                ['id'=>7502,'kode_kota'=>'7502','nama_kota'=>'KABUPATEN GORONTALO','id_provinsi'=>75],
                ['id'=>7503,'kode_kota'=>'7503','nama_kota'=>'KABUPATEN POHUWATO','id_provinsi'=>75],
                ['id'=>7504,'kode_kota'=>'7504','nama_kota'=>'KABUPATEN BONE BOLANGO','id_provinsi'=>75],
                ['id'=>7505,'kode_kota'=>'7505','nama_kota'=>'KABUPATEN GORONTALO UTARA','id_provinsi'=>75],
                ['id'=>7571,'kode_kota'=>'7571','nama_kota'=>'KOTA GORONTALO','id_provinsi'=>75],
                ['id'=>7601,'kode_kota'=>'7601','nama_kota'=>'KABUPATEN MAJENE','id_provinsi'=>76],
                ['id'=>7602,'kode_kota'=>'7602','nama_kota'=>'KABUPATEN POLEWALI MANDAR','id_provinsi'=>76],
                ['id'=>7603,'kode_kota'=>'7603','nama_kota'=>'KABUPATEN MAMASA','id_provinsi'=>76],
                ['id'=>7604,'kode_kota'=>'7604','nama_kota'=>'KABUPATEN MAMUJU','id_provinsi'=>76],
                ['id'=>7605,'kode_kota'=>'7605','nama_kota'=>'KABUPATEN MAMUJU UTARA','id_provinsi'=>76],
                ['id'=>7606,'kode_kota'=>'7606','nama_kota'=>'KABUPATEN MAMUJU TENGAH','id_provinsi'=>76],
                ['id'=>8101,'kode_kota'=>'8101','nama_kota'=>'KABUPATEN MALUKU TENGGARA BARAT','id_provinsi'=>81],
                ['id'=>8102,'kode_kota'=>'8102','nama_kota'=>'KABUPATEN MALUKU TENGGARA','id_provinsi'=>81],
                ['id'=>8103,'kode_kota'=>'8103','nama_kota'=>'KABUPATEN MALUKU TENGAH','id_provinsi'=>81],
                ['id'=>8104,'kode_kota'=>'8104','nama_kota'=>'KABUPATEN BURU','id_provinsi'=>81],
                ['id'=>8105,'kode_kota'=>'8105','nama_kota'=>'KABUPATEN KEPULAUAN ARU','id_provinsi'=>81],
                ['id'=>8106,'kode_kota'=>'8106','nama_kota'=>'KABUPATEN SERAM BAGIAN BARAT','id_provinsi'=>81],
                ['id'=>8107,'kode_kota'=>'8107','nama_kota'=>'KABUPATEN SERAM BAGIAN TIMUR','id_provinsi'=>81],
                ['id'=>8108,'kode_kota'=>'8108','nama_kota'=>'KABUPATEN MALUKU BARAT DAYA','id_provinsi'=>81],
                ['id'=>8109,'kode_kota'=>'8109','nama_kota'=>'KABUPATEN BURU SELATAN','id_provinsi'=>81],
                ['id'=>8171,'kode_kota'=>'8171','nama_kota'=>'KOTA AMBON','id_provinsi'=>81],
                ['id'=>8172,'kode_kota'=>'8172','nama_kota'=>'KOTA TUAL','id_provinsi'=>81],
                ['id'=>8201,'kode_kota'=>'8201','nama_kota'=>'KABUPATEN HALMAHERA BARAT','id_provinsi'=>82],
                ['id'=>8202,'kode_kota'=>'8202','nama_kota'=>'KABUPATEN HALMAHERA TENGAH','id_provinsi'=>82],
                ['id'=>8203,'kode_kota'=>'8203','nama_kota'=>'KABUPATEN KEPULAUAN SULA','id_provinsi'=>82],
                ['id'=>8204,'kode_kota'=>'8204','nama_kota'=>'KABUPATEN HALMAHERA SELATAN','id_provinsi'=>82],
                ['id'=>8205,'kode_kota'=>'8205','nama_kota'=>'KABUPATEN HALMAHERA UTARA','id_provinsi'=>82],
                ['id'=>8206,'kode_kota'=>'8206','nama_kota'=>'KABUPATEN HALMAHERA TIMUR','id_provinsi'=>82],
                ['id'=>8207,'kode_kota'=>'8207','nama_kota'=>'KABUPATEN PULAU MOROTAI','id_provinsi'=>82],
                ['id'=>8208,'kode_kota'=>'8208','nama_kota'=>'KABUPATEN PULAU TALIABU','id_provinsi'=>82],
                ['id'=>8271,'kode_kota'=>'8271','nama_kota'=>'KOTA TERNATE','id_provinsi'=>82],
                ['id'=>8272,'kode_kota'=>'8272','nama_kota'=>'KOTA TIDORE KEPULAUAN','id_provinsi'=>82],
                ['id'=>9101,'kode_kota'=>'9101','nama_kota'=>'KABUPATEN FAKFAK','id_provinsi'=>91],
                ['id'=>9102,'kode_kota'=>'9102','nama_kota'=>'KABUPATEN KAIMANA','id_provinsi'=>91],
                ['id'=>9103,'kode_kota'=>'9103','nama_kota'=>'KABUPATEN TELUK WONDAMA','id_provinsi'=>91],
                ['id'=>9104,'kode_kota'=>'9104','nama_kota'=>'KABUPATEN TELUK BINTUNI','id_provinsi'=>91],
                ['id'=>9105,'kode_kota'=>'9105','nama_kota'=>'KABUPATEN MANOKWARI','id_provinsi'=>91],
                ['id'=>9106,'kode_kota'=>'9106','nama_kota'=>'KABUPATEN SORONG SELATAN','id_provinsi'=>91],
                ['id'=>9107,'kode_kota'=>'9107','nama_kota'=>'KABUPATEN SORONG','id_provinsi'=>91],
                ['id'=>9108,'kode_kota'=>'9108','nama_kota'=>'KABUPATEN RAJA AMPAT','id_provinsi'=>91],
                ['id'=>9109,'kode_kota'=>'9109','nama_kota'=>'KABUPATEN TAMBRAUW','id_provinsi'=>91],
                ['id'=>9110,'kode_kota'=>'9110','nama_kota'=>'KABUPATEN MAYBRAT','id_provinsi'=>91],
                ['id'=>9111,'kode_kota'=>'9111','nama_kota'=>'KABUPATEN MANOKWARI SELATAN','id_provinsi'=>91],
                ['id'=>9112,'kode_kota'=>'9112','nama_kota'=>'KABUPATEN PEGUNUNGAN ARFAK','id_provinsi'=>91],
                ['id'=>9171,'kode_kota'=>'9171','nama_kota'=>'KOTA SORONG','id_provinsi'=>91],
                ['id'=>9401,'kode_kota'=>'9401','nama_kota'=>'KABUPATEN MERAUKE','id_provinsi'=>94],
                ['id'=>9402,'kode_kota'=>'9402','nama_kota'=>'KABUPATEN JAYAWIJAYA','id_provinsi'=>94],
                ['id'=>9403,'kode_kota'=>'9403','nama_kota'=>'KABUPATEN JAYAPURA','id_provinsi'=>94],
                ['id'=>9404,'kode_kota'=>'9404','nama_kota'=>'KABUPATEN NABIRE','id_provinsi'=>94],
                ['id'=>9408,'kode_kota'=>'9408','nama_kota'=>'KABUPATEN KEPULAUAN YAPEN','id_provinsi'=>94],
                ['id'=>9409,'kode_kota'=>'9409','nama_kota'=>'KABUPATEN BIAK NUMFOR','id_provinsi'=>94],
                ['id'=>9410,'kode_kota'=>'9410','nama_kota'=>'KABUPATEN PANIAI','id_provinsi'=>94],
                ['id'=>9411,'kode_kota'=>'9411','nama_kota'=>'KABUPATEN PUNCAK JAYA','id_provinsi'=>94],
                ['id'=>9412,'kode_kota'=>'9412','nama_kota'=>'KABUPATEN MIMIKA','id_provinsi'=>94],
                ['id'=>9413,'kode_kota'=>'9413','nama_kota'=>'KABUPATEN BOVEN DIGOEL','id_provinsi'=>94],
                ['id'=>9414,'kode_kota'=>'9414','nama_kota'=>'KABUPATEN MAPPI','id_provinsi'=>94],
                ['id'=>9415,'kode_kota'=>'9415','nama_kota'=>'KABUPATEN ASMAT','id_provinsi'=>94],
                ['id'=>9416,'kode_kota'=>'9416','nama_kota'=>'KABUPATEN YAHUKIMO','id_provinsi'=>94],
                ['id'=>9417,'kode_kota'=>'9417','nama_kota'=>'KABUPATEN PEGUNUNGAN BINTANG','id_provinsi'=>94],
                ['id'=>9418,'kode_kota'=>'9418','nama_kota'=>'KABUPATEN TOLIKARA','id_provinsi'=>94],
                ['id'=>9419,'kode_kota'=>'9419','nama_kota'=>'KABUPATEN SARMI','id_provinsi'=>94],
                ['id'=>9420,'kode_kota'=>'9420','nama_kota'=>'KABUPATEN KEEROM','id_provinsi'=>94],
                ['id'=>9426,'kode_kota'=>'9426','nama_kota'=>'KABUPATEN WAROPEN','id_provinsi'=>94],
                ['id'=>9427,'kode_kota'=>'9427','nama_kota'=>'KABUPATEN SUPIORI','id_provinsi'=>94],
                ['id'=>9428,'kode_kota'=>'9428','nama_kota'=>'KABUPATEN MAMBERAMO RAYA','id_provinsi'=>94],
                ['id'=>9429,'kode_kota'=>'9429','nama_kota'=>'KABUPATEN NDUGA','id_provinsi'=>94],
                ['id'=>9430,'kode_kota'=>'9430','nama_kota'=>'KABUPATEN LANNY JAYA','id_provinsi'=>94],
                ['id'=>9431,'kode_kota'=>'9431','nama_kota'=>'KABUPATEN MAMBERAMO TENGAH','id_provinsi'=>94],
                ['id'=>9432,'kode_kota'=>'9432','nama_kota'=>'KABUPATEN YALIMO','id_provinsi'=>94],
                ['id'=>9433,'kode_kota'=>'9433','nama_kota'=>'KABUPATEN PUNCAK','id_provinsi'=>94],
                ['id'=>9434,'kode_kota'=>'9434','nama_kota'=>'KABUPATEN DOGIYAI','id_provinsi'=>94],
                ['id'=>9435,'kode_kota'=>'9435','nama_kota'=>'KABUPATEN INTAN JAYA','id_provinsi'=>94],
                ['id'=>9436,'kode_kota'=>'9436','nama_kota'=>'KABUPATEN DEIYAI','id_provinsi'=>94],
                ['id'=>9471,'kode_kota'=>'9471','nama_kota'=>'KOTA JAYAPURA','id_provinsi'=>94],
        ];
        DB::table('kotas')->insert($kota);
    }
}
